### ISSUE TITLE
Custom Operator

### ISSUE THREAD

**Issue by nebhale** [pgjdbc/r2dbc-postgresql#2]
Having some experience doing this now, the client portion of the implementation (i.e. the portion that transforms Reactive Streams into wire-protocol) should be implemented as a custom operator.  This would allow the use of `onSubscribe()` to establish the connection, `cancel()` to terminate it, and `request()` to call for more data from a portal.  This is much easier to troubleshoot and more intuitive to maintain than the current nesting dolls of reactive flows.

**Comment by davecramer** [comment]
Can you give me an example of what you are looking to do here ?

**Comment by nebhale** [comment]
Yeah, this is a really hard one, and probably not suitable to pick up.  Effectively, we use that really complicated `*MessageFlow` and a bunch of `Processor`s to get data into and out of `reactor-netty`.  What needs to happen is that we have to write a custom Reactor operator (implement `Subscriber` and `Publisher` from scratch directly) and act as the reactive to wire-protocol bridge.  It'll be more efficient, more understandable, more debuggable, and better all around.  However, it take a ton of Reactor expertise to make it happen, which sucks.

**Comment by davecramer** [comment]
No worries, I've found a bunch of other stuff to work on.

The way we loop through oid's for instance
and binary encoder/decoders

**Comment by mp911de** [comment]
Closing this issue as we have a custom subscriber and `FluxDiscardOnCancel` in place that are sufficient for protocol handling.
