### ISSUE TITLE
add capability to log query parameters (bindings) values

### ISSUE THREAD

**Issue by 62mkv** [pgjdbc/r2dbc-postgresql#278]
#### Describe the solution you'd like

I'd like to be able to specify logging level (say, `io.r2dbc.postgresql.PARAM`) which, when set to DEBUG or TRACE, would enable logging of parameters. 

#### Describe alternatives you've considered

`r2bc-proxy` is an alternative, but seems to be a big overhead for such a simple use-case 

#### Teachability, Documentation, Adoption, Migration Strategy

A mention in the README should suffice as a documentation

**Comment by mp911de** [comment]
We do not record parameter values in a canonical format that is suitable for logging. When calling `bind(…)`, we run the bind value through the codec and the result is a `Publisher<ByteBuf>`. Therefore, we cannot really print any parameters during the execution.

We could add trace logging to the bind methods so that parameters get logged at the time of their binding.

**Comment by 62mkv** [comment]
that would be great!

**Comment by mp911de** [comment]
Feel free to submit a pull request.

**Comment by ttddyy** [comment]
FYI, with r2dbc-proxy, you can do something like this:

```java
MethodExecutionInfoFormatter formatter = new MethodExecutionInfoFormatter().addConsumer((execInfo, sb) -> {
  sb.append("params=");
  sb.append(StringUtils.arrayToCommaDelimitedString(execInfo.getMethodArgs()));
});

ConnectionFactory proxyConnectionFactory = 
  ProxyConnectionFactory.builder(connectionFactory)
    .listener(new LifeCycleListener() {
      @Override
      public void beforeBindOnStatement(MethodExecutionInfo methodExecutionInfo) {
        logger.info(formatter.format(methodExecutionInfo));
      }
      @Override
      public void beforeBindNullOnStatement(MethodExecutionInfo methodExecutionInfo) {
        logger.info(formatter.format(methodExecutionInfo));
      }
    })
    .build();
```
