### ISSUE TITLE
Support for geospatial types - point, line, box, polygon etc

### ISSUE THREAD

**Issue by avinash-anand** [pgjdbc/r2dbc-postgresql#282]
## Feature Request
Please don't mind as I'm a beginner wrt requesting OSS features.
I would like to have support for geo-spatial types like point, line, polygon etc.

#### Is your feature request related to a problem? Please describe
Our current project is JDBC based and there we use postgis-jdbc to save our data along with geospatial data in postgresql. we save mostly coordinates (Points) or lines or polygons for some markings done on maps. We were wondering if we can use r2dbc, if it had the support for these data types.

#### Describe the solution you'd like
I would like to have support for geospatial types of postgresql.

#### Geometry type support

- [x] `point` (#283)
- [ ] `line`
- [ ] `lseg`
- [ ] `box`
- [ ] `path` (open, closed)
- [ ] `polygon`
- [x] `circle` (#300)

**Comment by mp911de** [comment]
I'm not sure where the best place is for Postgres Geo functionality. The JDBC driver ships with Geo types (`PGline` and others), so likely we should follow the same model.

Feel free to submit a pull request containing this functionality.

**Comment by avinash-anand** [comment]
> I'm not sure where the best place is for Postgres Geo functionality. The JDBC driver ships with Geo types (`PGline` and others), so likely we should follow the same model.
> 
> Feel free to submit a pull request containing this functionality.

@mp911de , Thanks for your reply. If you could guide me little, I can give it a try. From where should I start?

**Comment by mp911de** [comment]
What seems required are two things:

* Declaration of Geo-objects. Take a look at the [`geometric`](https://github.com/pgjdbc/pgjdbc/tree/master/pgjdbc/src/main/java/org/postgresql/geometric) package of pgjdbc.
* Creation of dynamic codecs per Geo object type. I'm not familiar with Postgres Geo types, but as it looks now, Geometry types require an OID lookup similar to the `hstore` support. Have a look at [`BuiltinDynamicCodecs`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/BuiltinDynamicCodecs.java) that looks up Postgres types and registers codecs. See also the [`codec`](https://github.com/r2dbc/r2dbc-postgresql/tree/master/src/main/java/io/r2dbc/postgresql/codec) package for further reference.

Starting with a single codec for `line`, `point` or `circle` seems a good choice. Other than that, the [contribution guide](https://github.com/r2dbc/.github/blob/master/CONTRIBUTING.adoc) describes how to contribute by forking the repository and submitting a pull request.

**Comment by mp911de** [comment]
`Point` support was added with #283.

**Comment by mp911de** [comment]
We now support al geo-spatial types 🎉  as of 0.8.5.
