### ISSUE TITLE
Query doesn't complete

### ISSUE THREAD

**Issue by mosherobinov** [pgjdbc/r2dbc-postgresql#292]
#### Versions

- Driver: 0.8.4.BUILD-SNAPSHOT
- Database: PostgreSQL 12
- Java: 1.8.0_202
- OS: macOS Catalina 10.15.5

#### Current Behavior

query doesn't complete and doesn't emit all of the rows.
#### Steps to reproduce

i forked `r2dbc-postgresql` and added a new test that reproduce this issue.
take a look at this commit: https://github.com/mosherobinov/r2dbc-postgresql/commit/a679e8ee8a3af0124d68c98cc3c24d13c8970315 
seems to be some kind of a race between the `onNext()` and `request()` when they are happening on different threads, 
therefore i had to `publish` on a different scheduler and `limitRate` to 1 so the `onNext()` and `request()` will interleave.
the test times out after the query doesn't complete.

**Comment by x0a1b** [comment]
I can confirm this happening; this fix should be part of `0.8.4.RELEASE` build.

**Comment by mp911de** [comment]
Thanks a lot for the reproducer. I'm going to investigate what's going on.

**Comment by mp911de** [comment]
As it looks now, the emission gets stuck after `request(1)`. This is, because of missing upstream demand propagation (`hasBufferedItems() && hasDownstreamDemand()` doesn't allow entering `drainLoop`). Calling `demandMore()` helps to address the issue. Need to check whether that's the fix or whether we might miss something.

**Comment by mp911de** [comment]
0.8.4 snapshots are available from repo.spring.io. Feel free to test against the new snapshots.

**Comment by mosherobinov** [comment]
@mp911de Thanks, i will check it.
do we have a due date for the 0.8.4 release?

**Comment by mp911de** [comment]
Not yet. Roughly, we aimed for shipping releases every two months. Mid-July seems a good target.

**Comment by x0a1b** [comment]
Is it part of `0.8.4.BUILD-20200626.112115-12`; I can deploy it on prod and tell you if I see the issue again.

**Comment by x0a1b** [comment]
@mp911de  I have been trying to pull the SNAPSHOT build I am getting:

```
12:14:53     > Could not resolve io.r2dbc:r2dbc-postgresql:0.8.4.BUILD-20200626.112115-12.
12:14:53       Required by:
12:14:53           project :
12:14:53        > Could not resolve io.r2dbc:r2dbc-postgresql:0.8.4.BUILD-20200626.112115-12.
12:14:53           > Could not get resource 'https://repo.spring.io/snapshot/io/r2dbc/r2dbc-postgresql/0.8.4.BUILD-SNAPSHOT/r2dbc-postgresql-0.8.4.BUILD-20200626.112115-12.pom'.
12:14:53              > Could not GET 'https://www.jfrog.com/error?from=repo.spring.io&by=nginx-shared3c.gcoss-use1.jfrog.local'. Received status code 403 from server: Forbidden
12:14:53        > Could not resolve io.r2dbc:r2dbc-postgresql:0.8.4.BUILD-20200626.112115-12.
12:14:53           > Could not get resource 'http://repo.spring.io/plugins-release/io/r2dbc/r2dbc-postgresql/0.8.4.BUILD-SNAPSHOT/r2dbc-postgresql-0.8.4.BUILD-20200626.112115-12.pom'.
```

Gradle seems to be not able to resolve the dependency.

**Comment by mp911de** [comment]
repo.spring.io was impacted last night by an incident, see https://status.jfrog.io/incidents/cjx2djy9xzb2 for further details. The incident is resolved now.

**Comment by x0a1b** [comment]
Thanks it works now.

**Comment by mosherobinov** [comment]
i can confirm as well this issue is fixed now.
