### ISSUE TITLE
EnumCodec decoding fails if the requested value type is Object

### ISSUE THREAD

**Issue by mp911de** [pgjdbc/r2dbc-postgresql#302]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open-source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Problem

Retrieving a column value through`Row.get("my_enum_column")` fails for `EnumCodec`. `Row.get(identifier)` is a default method that forwards to `Row.get(identifier, Object.class)`. `EnumCodec` checks whether the requested type that it should decode with `Object.class.equals(theEnumType)`. 

## Solution

`EnumCodec.canDecode(…)` should check whether the requested type is assignable, similar to what [`AbstractCodec`](https://github.com/pgjdbc/r2dbc-postgresql/blob/a02015598d5793bda2a0e9d20302289771b2f3ff/src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java#L53) is performing the check. 

## Steps to Fix

- [ ] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/.github/CODE_OF_CONDUCT.adoc)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by rasikhinge** [comment]
Hi @mp911de , as this will be my first contribution in open source, I would like to claim this issue.

**Comment by mp911de** [comment]
Sure, you're welcome @rasikhinge. The first step is to build the project. Check out the local build section in the project readme. To run integration tests, you will need to install Docker on your machine. 

Once these things are done, ideally create a local feature branch and start changing the code.

**Comment by jpestana-projects** [comment]
Hi! I would like contribute with this issue (actually I think know how to solve the problem) but have some doubts about test my solution.
Firstly, how I should configure my enviroment to test the code? Should I configure any concrete Docker container?
Do I need to build any specific postgresql database? I mean, if any type of enum throws the error or it's more specific.

Thank you!

**Comment by mp911de** [comment]
Thanks for your interest @jpestana-projects. We haven't head back from @rasikhinge yet. Let's give them three more days until you can claim the issue.

If you're interested in running the build locally, then installing just Docker is fine. Everything else is handled by the project build infrastructure as we're using @testcontainers for integration testing that pulls an image during integration tests.

For this specific ticket, extending `EnumCodecUnitTests` should be sufficient.

**Comment by rasikhinge** [comment]
@mp911de , Sorry for late response, I am not available for this week, got some personal work, So I won't be able to contribute for this issue. You can re-assign this issue to @jpestana-projects. 
Thank you for giving me this opportunity.

**Comment by mp911de** [comment]
You're welcome and thanks for letting us know. @jpestana-projects feel free to start working on this ticket if you like.

**Comment by mp911de** [comment]
Thanks for your contribution @jpestana-projects.
