### ISSUE TITLE
How to execute a simple sql by r2dbc-postgresql

### ISSUE THREAD

**Issue by highgozhangyc** [pgjdbc/r2dbc-postgresql#311]
Hi everyone,
  I want to execute a simple sql by r2dbc-postgresql,and i wrote a simple example like this:

           PostgresqlConnectionFactory connectionFactory = new 
                   PostgresqlConnectionFactory(PostgresqlConnectionConfiguration.builder()
			    .host("localhost")
			    .port(5433)  // optional, defaults to 5432
			    .username("postgres")
			    .password("postgres")
			    .database("postgres")  // optional
			    .options(options) // optional
			    .build());

		Mono<PostgresqlConnection> connectionMono = Mono.from(connectionFactory.create());
		connectionMono.flatMapMany(connection -> connection
                .createStatement("INSERT INTO personwwwe (id, first_name, last_name) VALUES ($1, $2, $3)")
                .bind("$1", 1)
                .bind("$2", "Walter")
                .bind("$3", "White")
                .execute());

But,the sql cannot be executed in database,i did not use any spring module.So,i want know how to execute a simple sql by r2dbc-postgresql?Or what someting wrong did i do?
Thanks very much.

**Comment by mp911de** [comment]
R2DBC requires the consumption of the `Result` to ensure that a query gets executed. `Statement.execute()` typically creates a `Publisher<Result>` which represents an execution promise (i.e. the actual query is run when `Result` gets consumed)

**Comment by mp911de** [comment]
Closing the issue as it works as design.
