### ISSUE TITLE
open PostgresqlConnectionFactory

### ISSUE THREAD

**Issue by splix** [pgjdbc/r2dbc-postgresql#323]
#### Is your feature request related to a problem? Please describe

Right now the class `PostgresqlConnectionFactory` is set as `final`. It prevents unit tests from mocking it.

It's useful when you test a code that references the connection factory, but an actual db requests are not required for the test.

#### Describe the solution you'd like

- Make it non-final.
- Or make it an interface with `final` default implementation

**Comment by mp911de** [comment]
All of our implementation types are `final` to avoid subclassing and unintended usage. Please use `ConnectionFactory` instead. We also provide a public API package exposing interfaces in `io.r2dbc.postgresql.api`.
