### ISSUE TITLE
Add Interval Codec

### ISSUE THREAD

**Issue by HenrikHL** [pgjdbc/r2dbc-postgresql#345]
## Feature Request

Interval is a given datatype for Postgres.

#### Is your feature request related to a problem? Please describe

Using Interval for specifying a duration in time is a common practice.

#### Describe the solution you'd like

Create an IntervalCodec.

#### Describe alternatives you've considered

There are only two possible alternatives: add the codec as a default; add the codec as an extension. The latter is inferior because most of the underlying support needed to create a standalone codec is already present as abstract classes within the codec package. If the parent classes were public, then an extension could be built upon that base.

#### Teachability, Documentation, Adoption, Migration Strategy

This simply exposes a defined datatype.

**Comment by mp911de** [comment]
It makes sense to add a codec for interval values along with an own `Interval` type. JSR-310 `Period` and `Duration` aren't suited for exact interval values as they either cover value ranges roughly for days with `Duration`  or day-precision for `Period`.

Ideally, the interval type looks like `PGInterval` with options to create an interval from seconds to years values, `Duration`, and `Period` (and `Duration` and `Period`) and we can consume the interval parts as `Duration` (seconds/minutes/hours) and `Period` (days, months, years).

**Comment by frankgh** [comment]
I'm interested in contributing in this enhancement.

**Comment by mp911de** [comment]
Great to hear. Let us know if there's something we can assist you with.

**Comment by frankgh** [comment]
@mp911de I was able to do some research and get some code working. However, I am unable to force binary transfer. Even though my connection has the force binary transfer flag, I am reading intervals as text format only. I am working on the string parsing at the moment. If you have any suggestions on how to force binary transfer (or if binary is not supported for interval) please let me know.

**Comment by mp911de** [comment]
Paging @davecramer

**Comment by frankgh** [comment]
@mp911de I have opened a PR. I will probably be polishing it a little more, but the PR is ready to be reviewed.
