### ISSUE TITLE
Multiple conditional inserts of a new entity gives duplication error

### ISSUE THREAD

**Issue by skygup7** [pgjdbc/r2dbc-postgresql#351]
Let's consider this function

```kotlin
@Transactional
fun conditionalInsertEntity(dbEntity: DBEntity): Mono<DBEntity> {
    return fetchObjectByPublicId(dbEntity.publicId)
        .switchIfEmpty {
            r2DatabaseClient.insert()
                .into(DBEntity::class.java)
                .using(Flux.just(dbEntity))
                .fetch()
                .one()
                .map { it["entity_id"] as Long }
                .flatMap { fetchObjectById(it) }
        }
}
```

while running the above function with the following driver code I get duplicate entry errors if the list contains duplicates. Ideally, it shouldn't give that error because the above function is already handling the case for duplicate inserts!!

```kotlin
val result = Flux.fromIterable(//list of DBEntity objects)
    .flatMap { conditionalInsert(it) }
    .collectList()
    .block()
```

**Comment by mp911de** [comment]
When filing a bug report against the driver, please provide a reproducer that uses only driver API without using any 3rd party tools like spring.

**Comment by Squiry** [comment]
Anyway, you can try concatMap there.

**Comment by skygup7** [comment]
Thanks Squiry, concatMap certainly helps!!
