### ISSUE TITLE
Multi tenant support to switch schema for the existing datasource

### ISSUE THREAD

**Issue by ramneekh** [pgjdbc/r2dbc-postgresql#354]
## Feature Request

I would like to have the option to set the schema(search path) for the connection being used in the transaction.
Currently, schemas have to be pre-configured at the application startup. 

#### Is your feature request related to a problem? Please describe

For the multi-tenant approach, I want my app to support new tenant onboarding without any downtime/configuration change or adding any data source. another reason is I will have a large number of tenants so I can't have that many data sources/connection pools.

#### Describe the solution you'd like

I would like to override the getConnection or add/update the search path for the connection before the start of the transaction.

#### Describe alternatives you've considered

Any other solution where I don't have to update each and every query to prefix the schema or add a new data source for each new tenant.

**Comment by mp911de** [comment]
You should be able to achieve this by using pure SQL with `SET search_path="..."`.

**Comment by ramneekIncepta** [comment]
Can you please advise(example) how and where to set the `SET search_path="..."`?
Assuming it needs to be done on the connection before it executes a query.

I would like to avoid setting search_path in each and every query.

**Comment by ramneekh** [comment]
Can you please advise(example) how and where to set the SET search_path="..."?
Assuming it needs to be done on the connection before it executes a query.

I would like to avoid setting search_path in each and every query.

**Comment by davecramer** [comment]
```
Just wondering if the same connection can fetch data from two different schemas then why schema can't be specified somewhere at R2dbcEntityTemplate
```
What is your expectation there. If connection.setSchema were available you would have to call it to switch schema's

**Comment by ramneekIncepta** [comment]
> 
> What is your expectation there. If connection.setSchema were available you would have to call it to switch schema's
yes, that's not the best but option though. 
Depending on the tenant(schema) sent in the request header(oAuth), I would like to set the schema_path before the intended database operation. 
This was easily taken care of by hibernate, however missing in r2dbc.

**Comment by ramneekh** [comment]
> ```
> Just wondering if the same connection can fetch data from two different schemas then why schema can't be specified somewhere at R2dbcEntityTemplate
> ```
> 
> What is your expectation there. If connection.setSchema were available you would have to call it to switch schema's

yes, that's not the best but option though.
Depending on the tenant(schema) sent in the request header(oAuth), I would like to set the schema_path before the intended database operation.
This was easily taken care of by hibernate, however missing in r2dbc.

**Comment by davecramer** [comment]
Well from what I can tell the template doesn't support that option in the
API.

Dave Cramer

**Comment by mp911de** [comment]
> This was easily taken care of by hibernate, however missing in r2dbc.

Hibernate and JDBC/R2DBC are components situated at very different abstraction levels. Hibernate is an ORM library while JDBC and R2DBC are database drivers.

You should be able to call `Mono<Void> completed = connection.createStatement("SET search_path = …").execute().flatMap(Result::getRowsUpdated).then()`.

I'm not sure what else should be done here as we don't intend to expose each settable postgres variable through the API.

**Comment by ramneekh** [comment]
> You should be able to call `Mono<Void> completed = connection.createStatement("SET search_path = …").execute().flatMap(Result::getRowsUpdated).then()`.
> 

That's what I am doing leveraging Spring AOP so set the search_path every time. 
 
> I'm not sure what else should be done here as we don't intend to expose each settable postgres variable through the API.
Can you please share the reason for "we don't intend to expose "?
If required, I can contribute to working on this use case.

**Comment by mp911de** [comment]
We want to keep the API surface minimal. No one is happy with an API that exposes 100's methods (see https://www.postgresql.org/docs/current/runtime-config-client.html for reference of options that can be configured).

That being said, there's already a mechanism to update the runtime config so we're closing this ticket here.
