### ISSUE TITLE
26000 ERROR : prepared statement \"S_1\" does not exist

### ISSUE THREAD

**Issue by zhou-hao** [pgjdbc/r2dbc-postgresql#356]
when column type changed. execute SQL will throws 26000 ERROR :`prepared statement \"S_1\" does not exist`?

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
