### ISSUE TITLE
Decoding CopyOutResponse message does not comply with postgres documentation

### ISSUE THREAD

**Issue by igor-susic** [pgjdbc/r2dbc-postgresql#367]
#### Versions

- Driver: 0.8.X
- Database: docker:latest
- Java: 12
- OS: GNU/Linux

#### Current Behavior and Expected behavior/code

Documentation for `CopyOutResponse` at [postgres says:](https://www.postgresql.org/docs/current/protocol-message-formats.html)

> The format codes to be used for each column. Each must presently be zero (text) or one (binary). All must be zero if the overall copy format is textual.

And when I use `COPY some_table TO STDOUT;` I will receive byteBuff that has overall format of the text, but the code inside `AbstractCopyResponse` won't recognize this. In fact method `AbstractCopyResponse::readColumnFormats` in use case when the table has only two columns, for example, ID and some_text, it will receive count = 2 and in the switch statement it will ignore rest of the byteBuff which has two shortInt's with values of 0 and will go and set it to `Format.all()` which will make an assumption that it should be `Collections.unmodifiableSet(EnumSet.of(Format.FORMAT_BINARY, FORMAT_TEXT))`. Now maybe this is ok to work this way, but according to documentation and the decoding, the driver does not respect bytes sent by backend and instead of setting format to `Format.FORMAT_TEXT, FORMAT_TEXT` it set's the first one as binary.

#### Steps to reproduce

At forked repo I have added a unit test to reproduce the mentioned behavior:

- https://github.com/igor-susic/r2dbc-postgresql/blob/igor-susic/bug/decoding-copy-out-response/src/test/java/io/r2dbc/postgresql/message/backend/CopyOutResponseUnitTests.java#L59

And as I am trying to implement `COPY OUT` support, I need to know what is the way forward with this?

**Comment by davecramer** [comment]
The copy protocol is somewhat different than the normal protocol. Not sure you can just execute copy .. and expect it to work.

**Comment by davecramer** [comment]
Ok, looked at this and it looks like the error is in AbstractCopyResponse.readColumnFormats. It should not assume that a count of 2 automatically returns both formats. It should actually read the formats. Remove the switch and replace it with
```
+        Set<Format> formatSet = EnumSet.noneOf(Format.class);
+        for (int i = 0; i < count; i++) {
+            formatSet.add(Format.valueOf(in.readShort()));
         }
+
+        return formatSet;
+
```

**Comment by igor-susic** [comment]
Would it be enough to just remove:

```java
case 2:
    return Format.all();
```

I'm not sure why this exists at all, is there some use case that should be set like this without reading `byteBuff`?

**Comment by davecramer** [comment]
Case 1 makes no sense either. The loop below is correct

**Comment by igor-susic** [comment]
Yea you are right, I will remove those if that is ok and submit that.
