### ISSUE TITLE
Cannot decode value of type "short" error

### ISSUE THREAD

**Issue by nishant-1984** [pgjdbc/r2dbc-postgresql#372]
## Bug Report

Using R2DC along with kotlin and getting -> Cannot decode value of type "short" error. I tried all things like changing various versions of libraries, java and kotlin gives same error.

Dependencies below: (pom snippets)

<properties>
        <java.version>15</java.version>
        <kotlin.version>1.4.21</kotlin.version>
        <kotlin.couroutines.version>1.4.2</kotlin.couroutines.version>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
        <kotlin.code.style>official</kotlin.code.style>
    </properties>

<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.2.18</version>
</dependency>

<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-core</artifactId>
    <version>5.3.2</version>
</dependency>

<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-r2dbc</artifactId>
    <version>1.2.2</version>
</dependency>

<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-pool</artifactId>
    <version>0.8.5.RELEASE</version>
</dependency>
<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-spi</artifactId>
    <version>0.8.3.RELEASE</version>
</dependency>

<dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-postgresql</artifactId>
    <version>0.8.6.RELEASE</version>
</dependency>

<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-r2dbc</artifactId>
    <version>5.3.2</version>
</dependency>

Pojo where sql out is mapped

fun getByRow(row: io.r2dbc.spi.Row) = DashboardLeader(
            row.get("id", Integer::class.java)?.toInt(),
            row.get("handle", String::class.java),
            row.get("name", String::class.java),
            row.get("title", String::class.java) ?: THREE_DOTS,
            **row.get("creator_type", Short::class.java),**
            row.get("description", String::class.java),
            row.get("profile_image", String::class.java),
            row.get("n_kus", Int::class.java),
            row.get("n_followers", Int::class.java),
            row.get("n_plays", Int::class.java),
            row.get("badge_type", Short::class.java),
            row.get("approval_status", Short::class.java),
            row.get("moderated_at", Int::class.java),
            row.get("moderator_id", Int::class.java),
            row.get("creator_level", Short::class.java),
            row.get("user_profession_ids", IntArray::class.java)?.toList(),
            row.get("top_user_approval_status", Short::class.java),
            row.get("ops_log_data", String::class.java),
            row.get("rank", Int::class.java),
            row.get("exclude_bulk_follow", Boolean::class.java),
            row.get("bulk_follow_pref", Boolean::class.java),
            DashboardProfileReportDTO.getByRow(row)
)

Stack trace below: (getting error at decoding of line marked in bold)

Cannot decode value of type short
java.lang.IllegalArgumentException: Cannot decode value of type short
	at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:153)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.vokalapp.dashboard.controller.DashboardPeopleTabController#getDashboardPeopleTab(String, String, Integer, Integer, boolean, boolean, boolean, String, String, Boolean, Short, String, Integer, Boolean, Short, Mono) [DispatcherHandler]
Stack trace:
		at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:153)
		at io.r2dbc.postgresql.PostgresqlRow.decode(PostgresqlRow.java:90)
		at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:77)

**Comment by mp911de** [comment]
Care to attach your Schema so we can investigate what's happening?

**Comment by nishant-1984** [comment]
Postgres, **column creator_type smallint** is not getting parsed and above error is coming

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    handle character varying UNIQUE CHECK (handle::text !~~ ANY (ARRAY['%-%'::text, '%"%'::text, '%:%'::text, '%;%'::text, '%,%'::text, '%(%'::text, '%)%'::text, '%?%'::text, '%&%'::text, '%!%'::text, '%#%'::text, '%$%'::text, '%*%'::text])),
    social_profiles text,
    current_language smallint,
    auto_create boolean DEFAULT true,
    dob integer,
    modified_at integer,
    n_followers integer DEFAULT 0,
    n_plays integer DEFAULT 0,
    n_likes integer DEFAULT 0,
    n_kus integer DEFAULT 0,
    n_followings integer DEFAULT 0,
    n_shares integer DEFAULT 0,
    gender smallint,
    name character varying,
    push_token character varying,
    device_os smallint,
    channel smallint,
    title character varying,
    description text,
    status smallint DEFAULT '1'::smallint,
    profile_image text,
    email text,
    phone character varying(20),
    verified_at integer,
    last_daily_stat_notified_at integer,
    creator_type smallint,
    marital_status smallint,
    educational_qualifications text,
    work_exp text,
    communincation_prefs text,
    creation_source character varying(100),
    created_at integer,
    onesignal_id character varying,
    badge character varying,
    acquisation_source character varying(100),
    user_installation_id integer REFERENCES user_installations(id),
    show_on_feed boolean DEFAULT true,
    score bigint DEFAULT 0,
    visibility_prefs text,
    current_location_lat double precision,
    current_location_lon double precision,
    current_location character varying(150),
    native_location character varying(150),
    is_promoted boolean DEFAULT false,
    moderated_at integer,
    moderator_id integer REFERENCES users(id),
    moderation_remark text,
    is_quality boolean DEFAULT false,
    badge_type smallint,
    country_code integer,
    notification_preferences text DEFAULT '{}'::text,
    user_profession_id integer REFERENCES user_professions(id),
    user_info_meta text DEFAULT '{}'::text,
    has_co_users boolean DEFAULT false,
    use_on_feed_score boolean DEFAULT false,
    new_feed_version boolean DEFAULT false,
    section_type smallint DEFAULT '0'::smallint,
    profile_link character varying,
    role smallint DEFAULT '1'::smallint,
    chat_preference text DEFAULT '{}'::text,
    approval_status smallint DEFAULT 0,
    creator_level smallint,
    deleted_at integer,
    feed_algo smallint DEFAULT 0,
    session_on boolean DEFAULT false,
    highest_content_score integer DEFAULT 0,
    session_on_time integer DEFAULT 0,
    dob_date character varying(5),
    user_type smallint DEFAULT '0'::smallint,
    password_hash text,
    primary_mode smallint DEFAULT '1'::smallint,
    user_email character varying(320),
    user_registration_id integer REFERENCES user_registrations(id),
    encrypted_phone character varying(255),
    hashed_phone character varying(255),
    is_encrypted boolean DEFAULT false,
    last_active_day integer DEFAULT 0,
    feed_algorithm smallint DEFAULT '1'::smallint
);

**Comment by nishant-1984** [comment]
**[GLOBAL_ERROR] Cannot decode value of type [I
java.lang.IllegalArgumentException: Cannot decode value of type [I** , removed short field for testing now getting this error on **@Column("user_profession_ids") val occupationIds: List<Int>? = null, -> Integer Array** field.

**Comment by davecramer** [comment]
Can you provide us with a reproducible test case ?

**Comment by istarion** [comment]
I had these annoying errors with all primitive Java types.  
@nishant-1984 , try workaround: `row["creator_type"] as Short`  

You must know exact type for that (JDBCTemplate's rs.getInt() much more usefull)

**Comment by mp911de** [comment]
Note that `int[]` isn't supported (primitive array, and won't likely be supported anytime soon). We only support `Integer[]` (boxed array).

**Comment by mp911de** [comment]
Java primitive types aren't supported as decode type. Please use boxed (wrapper) types.

**Comment by julien-piccaluga** [comment]
So basically mapper function is not usable in Kotlin?

**Comment by mp911de** [comment]
> So basically mapper function is not usable in Kotlin?

I don't know Kotlin well enough to answer that question and I don't know how to refer to Java wrapper types from Kotlin. R2DBC SPI built to be used by frameworks and tools and not by application developers directly, hence some design restrictions apply.

**Comment by julien-piccaluga** [comment]
@mp911de when running Kotlin on the java platform, numbers are physically stored as JVM primitive type but it's not a big deal as we can force to use boxed representation by using `Long::class.javaObjectType` instead of `Long::class.java`.
