### ISSUE TITLE
We need to add java.util.Currency support

### ISSUE THREAD

**Issue by DmitryErmolchik** [pgjdbc/r2dbc-postgresql#375]
#### Is your feature request related to a problem? Please describe

I'm building a pet-project with java.util.Currency field and I was wondered r2dbc-postgresql doesn't support this basic data type.

#### Describe the solution you'd like

I propose to create a new codec **class CurrencyCodec extends AbstractCodec<Currency>** which will extract java.util.Currency.currencyCode and store it as a VARCHAR type.

#### Teachability, Documentation, Adoption, Migration Strategy

This is the new feature, no migration required.

**Comment by mp911de** [comment]
We don't want to add type support in the core for every available Java core type, therefore, declining this feature request.
