### ISSUE TITLE
Unable to insert a new entity in a table containing name "returning"

### ISSUE THREAD

**Issue by aryadnasauchyts** [pgjdbc/r2dbc-postgresql#377]
## Bug Report

Unable to insert a new entity in a table containing name "returning". The following error observed:
`Statement already includes RETURNING clause`

#### Versions

- Driver: 0.8.6
- Database: Postgres 11.6
- Java: 11
- OS: Mac OS Big Sur

#### Current Behavior

After debugging the guts of the driver I have found that GeneratedValuesUtils#hasReturningClause pattern matcher incorrectly identifies sql query

`INSERT INTO returning_user (id, name, user_details) VALUES ($1, $2, $3)` 

like having returning clause even though it does not have it. 

Looks like RETURNING clause matcher needs to be adjusted for such cases.
<details>
<summary>Stack trace</summary>

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: Statement already includes RETURNING clause
Caused by: java.lang.IllegalStateException: Statement already includes RETURNING clause
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.returnGeneratedValues(ExtendedQueryPostgresqlStatement.java:129)
```
</details>
 

#### Expected behavior/code

It's possible to insert records in a table having "returning" in its name.

**Comment by mp911de** [comment]
Care to submit a pull request to address the issue?

**Comment by govi20** [comment]
Hi, @mp911de would it be fine, If I work on it?

**Comment by mp911de** [comment]
Sure. Contributions are always welcome.

**Comment by govi20** [comment]
Thanks. 

One thing I came across, we are using a regex in `GeneratedValuesUtils.isSupportedCommand` which may cause an issue:

- if an unsupported command's table name contains insert/delete/delete words
- if nested query performs insert/update/delete operation. But the outer query performs an unsupported operation.
