### ISSUE TITLE
Special characters inside HStore columns are not read correctly

### ISSUE THREAD

**Issue by JoseLion** [pgjdbc/r2dbc-postgresql#407]
#### Versions

- Driver: 0.8.8
- Database: 13.0
- Java: 15.0.1
- OS: Windows

#### Current Behavior

If an HStore column contains data with special characters like `"a"=>"Zoë", "é"=>"Foo"`, the special characters are not read correctly. It looks like some bytes are lost right after decode because the result of the example above will be `{"a"="Zoￃﾫ", "ￃﾩ"="Foo"}`.
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TABLE hstoretest (
  id SERIAL NOT NULL PRIMARY KEY,
  data HSTORE NOT NULL
);
```

</details>

#### Steps to reproduce

To reproduce the issue, create a table with an HStore column, create a row, and add some special characters to the HStore column (like `"a"=>"Zoë", "é"=>"Foo"`). Fetch the data from Java code and check the result.

#### Expected behavior/code

Special characters should be decoded correctly. This means a column containing `"a"=>"Zoë", "é"=>"Foo"` should decode to a Map containing `{"a"="Zoë", "é"="Foo"}`.

#### Possible Solution

Avoid casting from `byte` to `char` while parsing the data. Special characters are usually 2 bytes long and a cast can effectively cut off information from the character.

**Comment by KeyZJ** [comment]
+1

**Comment by Nufirdy** [comment]
+1

**Comment by M00n1ight** [comment]
+1

**Comment by DenisTerentyev** [comment]
+1
