### ISSUE TITLE
Performance improvement on codec mapping 

### ISSUE THREAD

**Issue by frdeboffles** [pgjdbc/r2dbc-postgresql#409]
## Feature Request

While using this driver for fetching many rows from our table I noticed it was taking quite some time to build the `Row` objects. I hooked a profiler to the code and noticed it was spending quite some time for each row on the `codec.canDecode` method.
I wrote this little perf test to validate this finding:

```java
  @Test
  public void perfTestDecode() {
    DefaultCodecs codecs = new DefaultCodecs(TEST);
    long t = System.currentTimeMillis();
    for (int i = 0; i < 100000; i++) {
      for (int c = 0; c < 20; c++) {
        assertThat(
            codecs.decode(
                TEST.buffer(4).writeInt(100), INT4.getObjectId(), FORMAT_BINARY, Integer.class))
            .isEqualTo(100);
        assertThat(
            codecs.decode(
                ByteBufUtils.encode(TEST, "100"), INT2.getObjectId(), FORMAT_TEXT, Short.class))
            .isEqualTo((short) 100);
        assertThat(
            codecs.decode(
                ByteBufUtils.encode(TEST, "test"),
                VARCHAR.getObjectId(),
                FORMAT_TEXT,
                String.class))
            .isEqualTo("test");
        assertThat(
            codecs.decode(
                ByteBufUtils.encode(TEST, "2018-11-04 15:35:00.847108"),
                TIMESTAMP.getObjectId(),
                FORMAT_TEXT,
                LocalDateTime.class))
            .isInstanceOf(LocalDateTime.class);
        assertThat(codecs.decode(ByteBufUtils.encode(TEST, "{100,200}"), INT2_ARRAY.getObjectId(), FORMAT_TEXT, Object.class)).isEqualTo(new Short[]{100, 200});
        assertThat(codecs.decode(ByteBufUtils.encode(TEST, "{100,200}"), INT4_ARRAY.getObjectId(), FORMAT_TEXT, Object.class)).isEqualTo(new Integer[]{100, 200});
      }
    }
    System.out.println("Run in " + (System.currentTimeMillis() - t) + "ms");
  }
```
Running this on my machine results in:
```
Run in 13231ms
```
> NOTE That running the same example from 0.8.7.RELEASE results in 
> ```
> Run in 10389ms
> ```
> So it seems like the decoding performance went down between this release and the current master (at commit 9c773c8824b813e1ef65a26f18eadf97930a2933)

#### Is your feature request related to a problem? Please describe

I would rather use this driver and webflux than going the web mvc route and jdbc.

#### Describe the solution you'd like

I think the class `DefaultCodecs` would benefits from some simple caching mechanism. 
I did implement a simple caching (PR to come) and the results of the above test comes to:

```
Run in 7294ms
```

#### Describe alternatives you've considered

I haven't found alternatives

#### Teachability, Documentation, Adoption, Migration Strategy

NA

**Comment by mp911de** [comment]
Thanks a lot for your suggestion. I had something like this on my mind since iterations aren't really efficient to determine a codec.

**Comment by protyay** [comment]
@mp911de Interested to work in this project. Are you accepting new contributors ?

**Comment by mp911de** [comment]
Sure. Feel free to pick an issue, submit a pull request or participate in issue discussions.
