### ISSUE TITLE
Memory Leak of BalancedResolverGroup

### ISSUE THREAD

**Issue by johnsiu** [pgjdbc/r2dbc-postgresql#412]
## Bug Report

- Driver: 0.8.8
- Database: n/a
- Java: n/a
- OS: n/a

#### Current Behavior

<details>
<summary>Stack trace</summary>

```
// your stack trace here
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
-- your SQL here;
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

#### Expected behavior/code

We use this library in our project and found a memory leak.
Heap dumps were taken and it was discovered that there were many many instances of `BalancedResolverGroup` in `EpollEventLoop.terminationFuture.listeners.listeners`.  It doesn't help that a new `BalancedResolverGroup` is created whenever a connection is acquired. Whenever `BalancedResolverGroup.getResolver()` is called, a new listener is added to the EventLoop's termination listeners.
see https://github.com/netty/netty/blob/netty-4.1.65.Final/resolver/src/main/java/io/netty/resolver/AddressResolverGroup.java#L89

#### Possible Solution

`AddressResolverGroup` should almost always be a singleton.
This line should use the static instance (`BalancedResolverGroup.INSTANCE`) rather than instantiating.
https://github.com/pgjdbc/r2dbc-postgresql/blob/v0.8.8.RELEASE/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L392

**Comment by kitaev** [comment]
Hello @johnsiu 

I have encountered this leak too. Did you manage to find a workaround besides patching r2dbc-postgres?

**Comment by kitaev** [comment]
@mp911de I think another option to fix this leak would be to call `BalancedResolverGroup.close()` in `ReactorNettyClient.handleClose()` method.

**Comment by mp911de** [comment]
Feel free to submit a pull request. Leaving `BalancedResolverGroup ` open is clearly a bug on our side.

**Comment by kaladhar-mummadi** [comment]
@mp911de 
When Is 0.8.9 scheduled to be released ? We are facing the same issue.
