### ISSUE TITLE
PostgresObjectId#isValid uses exception as control mechanism resulting in significant performance penalty

### ISSUE THREAD

**Issue by amoffet** [pgjdbc/r2dbc-postgresql#420]
#### Versions

- Driver: 0.9.0.M1
- Database: Postgres 12
- Java: 1.8
- OS: OSX

#### Current Behavior

When using a custom type such as ENUM for a column, it will be assigned an object id that is not in the usual range.  The code in PostgresObjectId#isValid looks like this:

```
        if (objectId >= 0 && objectId < OID_CACHE_SIZE) {
            PostgresqlObjectId oid = CACHE[objectId];
            return oid != null;
        }

        try {
            valueOf(objectId);
            return true;
        } catch (Exception e) {
            return false;
        }
```

As a result, any row that has a custom type (such as enum) will now go through the exception path (to return false), which is expensive.  In my particular case, it results in 88,877 exceptions in 2 minutes.

It seems like #isValid should not depend on the exception throwing behavior of #valueOf and should return true or false directly.

<details>
<summary>Stack trace</summary>

```
// your stack trace here
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
-- your SQL here;
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

**Comment by amoffet** [comment]
Perhaps something as easy as:

```
    public static boolean isValid(int objectId) {

        if (objectId >= 0 && objectId < OID_CACHE_SIZE) {
            PostgresqlObjectId oid = CACHE[objectId];
            return oid != null;
        }

        for (PostgresqlObjectId type : values()) {
            if (type.objectId == objectId) {
                return true;
            }
        }
        return false;
    }
```
which is essentially the same code...

**Comment by mp911de** [comment]
Thanks for reporting the issue. Calling values() copies the internal value array so the check isn't ideal. Maybe we can increase the cache size to cover the full range and get away with a bit increased memory size in return for avoiding exceptions and allocations on the hot code path.

**Comment by Squiry** [comment]
Why do we even bother iterating values with known ids? No value can be there that is greater than `OID_CACHE_SIZE`. Block
```java
try {
    valueOf(objectId);
    return true;
} catch (Exception e) {
    return false;
}
```
always returns false now, doesn't it?

**Comment by mp911de** [comment]
It seems that `2951` is the highest OID that we have here so we could safely rely on the cache without employing any kind of iteration. Maybe also add a sanity check if someone adds another OID that is higher than `OID_CACHE_SIZE`.

**Comment by Squiry** [comment]
`3807` for `JSON` is the highest. Yep, sanity check is already provided [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/9c773c8824b813e1ef65a26f18eadf97930a2933/src/main/java/io/r2dbc/postgresql/codec/PostgresqlObjectId.java#L403): if any oid is greater we will get array exception.

**Comment by mp911de** [comment]
D'oh, I looked three times at the enum and couldn't spot JSON. Thanks for that.

**Comment by amoffet** [comment]
It looks like the cache is only created once and is never updated.  if the value is in the cache, it should be "valid", if not then it should not be "valid".  ```   public static boolean isValid(int objectId) {

        if (objectId >= 0 && objectId < OID_CACHE_SIZE) {
            PostgresqlObjectId oid = CACHE[objectId];
            return oid != null;
        }
        return false;
    }
```
would work then, since OID_CACHE_SIZE is already larger than JSON.  Am I missing anything?

**Comment by mp911de** [comment]
The code above should be the one to perform the check. I think the original issue is created because both checks (cache, valueOf) do not yield a hit.

**Comment by Squiry** [comment]
I think `valueOf(int)` should be fixed too. It can use check from `isValid(int)` and then just return cached value.
