### ISSUE TITLE
Driver doesn't properly handle canceling of the subscriber

### ISSUE THREAD

**Issue by dstepanov** [pgjdbc/r2dbc-postgresql#428]
0.8.8.RELEASE

I don't properly understand what is going on but my assumption is that in some cases when `Flux` is converted to `Mono`, the first result is taken and the upstream is closed which leads to a log warning and inconsistent state - in some cases transaction is not fully committed.

This test in Micronaut data shows the code that is causing the problems:
https://github.com/micronaut-projects/micronaut-data/blob/ddf11c1e8a7a27a1f6765cc5e1c1c3d3f74b475f/data-r2dbc/src/test/groovy/io/micronaut/data/r2dbc/PlainR2dbcSpec.groovy#L69-L92

You can see the warning when executed:

```
2:55:52.293 [reactor-tcp-nio-4] DEBUG io.r2dbc.postgresql.QUERY - Executing query: SELECT oid, typname FROM pg_catalog.pg_type WHERE typname IN ('hstore')
12:55:52.297 [reactor-tcp-nio-4] DEBUG io.r2dbc.postgresql.QUERY - Executing query: BEGIN
12:55:52.299 [reactor-tcp-nio-4] DEBUG io.r2dbc.postgresql.QUERY - Executing query: INSERT INTO author (name) VALUES ($1)
12:55:52.302 [reactor-tcp-nio-4] DEBUG io.r2dbc.postgresql.QUERY - Executing query: COMMIT
12:55:52.304 [reactor-tcp-nio-4] WARN  reactor.core.publisher.FluxUsingWhen - Async resource cleanup failed after cancel
io.r2dbc.postgresql.client.ReactorNettyClient$PostgresConnectionClosedException: Connection closed
```

The problem was causing an inconsistent state when our test-suite was running on the Github Actions and sometimes locally. The test-suite is mostly doing the blocking to extract the result because it's shared with JDBC tests, you may argue that that's not the correct way to do r2dbc. The solution was to eliminate any kind of upstream canceling by using `Flux`'s and `collectList`, which did solve the problem https://github.com/micronaut-projects/micronaut-data/pull/1076.

The same problem occurs in SQL-server and MySQL drivers.

**Comment by mp911de** [comment]
`Mono.from(…)` sends a cancellation to the subscription after receiving the first element. The resulting behavior is that once a cancellation was sent, you can no longer await the activity that is associated with the `Publisher` (e.g. `COMMIT` happens asynchronously). That isn't a driver issue, it's the behavior that you get from using `Mono.from(…)`. In Spring Framework, we solved the issue by inspecting whether the return type of a method is `Mono` and then use `Mono.usingWhen(…)` and `Mono.fromDirect(…)` to avoid the cancel-on-item behavior.

**Comment by dstepanov** [comment]
Thanks, it's good to know that it's expected but as the API user I don't see it as a good thing, I would expect the basic `Flux` to `Mono` transformation to work, maybe the framework could print a warning that canceling a connection subscriber is not a correct usage.

**Comment by mp911de** [comment]
It's not wrong per-se to cancel a subscription. It's more what comes after that. In your case, you're closing the connection without awaiting completion.

**Comment by dstepanov** [comment]
Yeah, I understand the cancellation is non-waiting. Maybe it would be nice to have a warning about this case or an exception.

**Comment by mp911de** [comment]
As per the Reactive Streams spec, as per [§3.13 of the spec](https://github.com/reactive-streams/reactive-streams-jvm#3-subscription-code):

> While the Subscription is not cancelled, Subscription.cancel() MUST request the Publisher to eventually drop any references to the corresponding subscriber.

There were some intentions to allow cancellation and await completion but Reactive Streams should represent a utility for computation and resource management was intentionally not considered in the design of Reactive Streams. The entire area regarding awaiting and resources is pretty brittle. In Spring Framework's reactive transaction management, there was initially commit on cancel behavior (assuming operators like `take(…)` and similar) until it became clear that `cancel` can be also issued by a connection timeout and that would lead to partially committed transactions. That behavior was eventually changed to rollback on cancel.

There's nothing we can do from a driver side. If you want to discuss `Flux`/`Mono` behavior, then [Project Reactor](https://github.com/reactor/reactor-core/issues) is the right place.
