### ISSUE TITLE
Adding Extension from Option

### ISSUE THREAD

**Issue by prtnv** [pgjdbc/r2dbc-postgresql#433]
Hi,
I know that extensions can be registered using java `ServiceLoader`. But I think it would be useful to be able to register them with options mechanism. For example, with this it can be configured from the Spring Boot `ConnectionFactoryOptionsBuilderCustomizer`. 

That could be provided by an Option with collection of extensions (`Option<Iterable<Extension>>`) that applyed in `PostgresqlConnectionFactoryProvider`.

Alternatively,  that could be provided by an Option with builder customizer, eg `Option<Consumer<Builder>> ` that called at the end of builder configartion in `PostgresqlConnectionConfiguration#fromConnectionFactoryOptions`. With this, in addition to adding extensions, we can change any other setting.

What do you think about this?

Thanks!

**Comment by mp911de** [comment]
That makes sense. We have other places where we accept Java objects (`options`, `sslHostnameVerifier`) so adding extensions would work here too. Feel free to submit a pull request.

Out of curiosity, what kind of extensions are you using/willing to register?

**Comment by prtnv** [comment]
@mp911de For exmaple, I want to register a set of CodecRegistrars to add custom pg enums support. I use spring and  i additionally need to to add custom enum writing converter. For that i want to place implemantation of CodecRegister and converter in one bean for each enum and inject all impementations to r2dbc connection factory and spring.
