### ISSUE TITLE
Remove restriction on ending semicolon in ExtendedQueryPostgresStatement

### ISSUE THREAD

**Issue by jogoussard** [pgjdbc/r2dbc-postgresql#439]
## Bug Report

The code at https://github.com/pgjdbc/r2dbc-postgresql/blob/835178b7214198a745b0d1169ae46c55ff7af0e9/src/main/java/io/r2dbc/postgresql/ExtendedQueryPostgresqlStatement.java#L159
that checks whether an extended query is valid or not will accept
`INSERT INTO mytable (id) VALUES ($1)`
but reject
`INSERT INTO mytable (id) VALUES ($1);`
because of the trailing semicolon, though AFAIK the two statements are equivalent in postgres.

The code should be rewritten along the lines of
```
return !sql.trim().isEmpty() && (!sql.contains(";") || sql.indexOf(";") == sql.length()-1) && sql.contains("$1");
```

#### Versions

- Driver: 0.8.8
- Database: Postgres 13
- Java: 15
- OS: AWS linux

#### Current Behavior

SQL ending in semi-colon are rejected.
 
#### Table schema

N/A

#### Steps to reproduce

Just use a Spring repository with a method using `@Query` with a ending semi-colon

#### Expected behavior/code

An ending semi-colon should not be taken into account

#### Possible Solution

See desc.

**Comment by Squiry** [comment]
You should check that last char of a _trimmed_ string is a semicolon and result of `indexOf` should be used as a replacement of `contains` but yeah, change looks correct.
