### ISSUE TITLE
Time-related integration tests failing

### ISSUE THREAD

**Issue by toverdijk** [pgjdbc/r2dbc-postgresql#467]
## Bug Report

Time-related integration tests failing in both CodecBinaryFormatIntegrationTests and CodecTextFormatIntegrationTests. 

#### Versions

- Driver: 42.3.1
- Database:  13.3
- Java: Amazon Corretto 11.0.13 / Amazon Corretto 17.0.1
- OS: Windows 10 Build 19042

#### Current Behavior

When running time-related unit tests, they fail:

<details>
<summary>Stack trace example:</summary>

```
org.opentest4j.AssertionFailedError: 
expected: 06:37:18.602257900Z
 but was: 06:37:18.602258Z

```
</details>
 
#### Table schema

n/a

#### Steps to reproduce

Just run the integration tests on above OS/JDK

#### Expected behavior/code

The integration tests should pass

#### Possible Solution

Postgresql stores time with microsecond resolution, whereas the OS/JDK used retrieves the time in the java 8 java.time package with nanosecond resolution with 100 nanosecond precision. This causes the time-related integration to fail unless the nanosecond part is zero (which happens 1 in 10 times).

Since postgresql "only" stores microseconds, we could change the tests to assert with the `isEqualToIgnoringNanos(..)` instead of `isEqualTo(..)` function.

A second option is, instead of relying on `LocalDateTime.now()` (and similar functions in other time-classes), to test with manually constructed times - such as `LocalDateTime.of(...)` without setting nanos. I think the first option is better.

#### Additional context

n/a

**Comment by mp911de** [comment]
Thanks for bringing this up. Since you have already looked into it, how about submitting a pull request that truncates nanos to zero in these tests?

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and backported now.
