### ISSUE TITLE
Support for postgis geometry parent type

### ISSUE THREAD

**Issue by javieronsurbe** [pgjdbc/r2dbc-postgresql#483]
## Feature Request
PostGIS have support to define a generic geometry type for fields that can contains points, polygons, etc. and this kind of field is supported in Postgres JDBC version using an [abstract class](https://github.com/postgis/postgis-java/blob/main/postgis-jdbc-geometry/src/main/java/net/postgis/jdbc/geometry/Geometry.java) that specific ones can inherit.

Can we have some similar behavior in r2dbc one? I.e.-  Declaring a field in a POJO of type Geometry (abstract) and when it is recovered from database from a table field of type geometry it is mapped to a specific type (Point, Polygon, etc.) 

As I see specific ones support are added (0.8.5 version), maybe it's not very difficult to add this enhancement to driver

Thanks!

**Comment by mp911de** [comment]
R2DBC's extension model is based on codecs so plugin authors can bring their own type hierarchy. Looking though the code of Postgis JDBC, I haven't found how Postgis registers itself with the JDBC driver. I think you could reuse the same types and provide a Postgis codec to natively read into Geometry types and write such.

Take a look at the `HSTORE` codec that is being registered conditionally if `HSTORE` is present: https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/BuiltinDynamicCodecs.java#L32

**Comment by javieronsurbe** [comment]
Thank you very much for the hint Mark. I will try it.
