### ISSUE TITLE
Consider lowercase `sslmode` for easier JDBC URL adaption

### ISSUE THREAD

**Issue by nhajratw** [pgjdbc/r2dbc-postgresql#486]
## Bug Report

Migrating from jdbc to r2dbc is confusing due to the jdbc parameter of `sslmode` and r2dbc requiring it to be cased differently as `sslMode` -- Ideally they should be the same, but at a minimum, i'd suggest a warning during URL parsing to indicate that the case differs.

#### Current Behavior

parameter `sslmode` does not work.

parameter `sslMode` works.

**Comment by mp911de** [comment]
Parameter compatibility with JDBC was never a goal. However, this seems a small change to additionally consider lowercase `sslmode`. Feel free to submit a pull request, see https://github.com/pgjdbc/r2dbc-postgresql/blob/40c2be0c9d5bfe67ffe69ad1e9c9fdb49a7f67b7/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java#L181.

**Comment by govi20** [comment]
@mp911de this change won't be backward compatible. shouldn't it be part of a major version release right?

**Comment by mp911de** [comment]
It should be. The approach is to introduce another constant and check it as fallback instead of replacing the existing constant for the option name.
