### ISSUE TITLE
Create Statement (Memory Leak)

### ISSUE THREAD

**Issue by toaster33** [pgjdbc/r2dbc-postgresql#502]
## Bug Report

Memory appears to be consumed and not released when using Create Statement.

#### Versions

- Driver: 0.9.1
- Database: 13.6
- Java: 17
- OS: Heroku, Standard 1GB

```
-XX:MaxDirectMemorySize=128m
-XX:MaxMetaspaceSize=128m
-Xss512k
-Dio.netty.allocator.type=unpooled
-Dio.netty.maxDirectMemory=512000
-Djdk.nio.maxCachedBufferSize=512000
-XX:+UseContainerSupport
-XX:CICompilerCount=2
-Dfile.encoding=UTF-8
-Xmx512m 
```
#### Current Behavior

Using the snippet below leads to high memory consumption.

<details>
<summary>Stack trace</summary>

```
2022-03-29T04:48:28.730757+00:00 heroku[web.1]: Process running mem=1028M(100.4%)
2022-03-29T04:48:28.750139+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

</details>
 
#### Table schema
Rule Table
Column: id, type UUID
Column id1, varchar(25)
Column id2,  varchar(25)
Column rule, varchar(5)

<details>
<summary>Input Code</summary>

```sql
CREATE TABLE IF NOT EXISTS public.rules
(
    id uuid NOT NULL,
    id1 character varying(25) COLLATE pg_catalog."default" NOT NULL,
    id2 character varying(25) COLLATE pg_catalog."default" NOT NULL,
    rule character varying(5) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rules_pkey PRIMARY KEY (id)
)
```

</details>

#### Steps to reproduce

Using 200k rows and inserting 7250 rows at a time (anything more would throw an error).
Every minute: delete all rows then reload the 200k rows.

<details>
<summary>Input Code</summary>

```java
public static final String SQL_INSERT_BASE =
		"INSERT INTO public.rules ("
		+ "id, "
		+ "id1, "
		+ "id2, "
		+ "rule) "
		+ "VALUES ";

public static Mono<Object> saveBulk(
    ConnectionFactory connectionFactory,
    List<Rules> list) {

  return Mono
        .from(connectionFactory.create())
        .map(connection -> {

          StringBuilder insert = new StringBuilder(SQL_INSERT_BASE);
          int values = 1;
          for (Rules one: list) {
            insert.append(
          "("
              + "$" + values++ + ", "
              + "$" + values++ + ", "
              + "$" + values++ + ", "
              + "$" + values++ + " "
          + "), ");
          }
          insert.deleteCharAt(insert.lastIndexOf(","));
          Statement statement = connection.createStatement(insert.toString());

          int bind = 0;
          for (Rules one: list) {

            statement.bind(bind++, one.getId());
            statement.bind(bind++, one.getId1());
            statement.bind(bind++, one.getId2());
            statement.bind(bind++, one.getRule());
          }

      return Mono
          .from(statement.returnGeneratedValues("id").execute())
          .flatMap(result -> Mono.from(result.getRowsUpdated()))
          .thenMany(connection.close())
          .doOnError((error) -> connection.close())
          .subscribe();
        });
}
```

</details>

#### Expected behavior/code

Memory consumption should revert to levels before the createStatement() was executed.

#### Possible Solution

Temporarily switched to createBatch() -
```java
public static final String SQL_INSERT_BASE =
		"INSERT INTO public.rules ("
		+ "id, "
		+ "id1, "
		+ "id2, "
		+ "rule) "
		+ "VALUES ";

public static Mono<Object> saveBulk(
    ConnectionFactory connectionFactory,
    List<Rules> list) {

  return Mono
        .from(connectionFactory.create())
        .map(connection -> {

          StringBuilder insert = new StringBuilder(SQL_INSERT_BASE);
          for (Rules one: list) {
            insert.append("(")
              .append("'")
              .append(one.getId())
              .append("', ")
              .append("'")
              .append(one.getId1())
              .append("', ")
              .append("'")
              .append(one.getId2())
              .append("', ")
              .append("'")
              .append(one.getRule())
              .append("''), ");
          }
          insert.deleteCharAt(insert.lastIndexOf(","));
          Batch statement = connection.createBatch().add(insert.toString());

      return Mono
          .from(statement.execute())
          .map(result -> result.getRowsUpdated())
          .thenMany(connection.close())
          .doOnError((error) -> connection.close())
          .subscribe();
        });
}
```

#### Additional context
Memory heap while using createStatement() and binding() -
<img width="293" alt="before" src="https://user-images.githubusercontent.com/2971768/160537859-608e45b7-1294-41f8-aa1e-507d58d0494b.png">

Memory heap while using createBatch() -
<img width="342" alt="after" src="https://user-images.githubusercontent.com/2971768/160537878-3a2a569b-c1b6-4704-83f2-19b6f2083785.png">

**Comment by Squiry** [comment]
1. You should not use that gigantic sql with thousands of bindings, you should use one prepared statement and add bindings for each row (almost like you did with batch statement):
2. Usually we do not call `subscribe`, especially when method returns mono: we use `flatMap`, `concatMap`, etc. 
3. To ease usage of `Connection` and other resources reactor provides `Mono.usingWhen` method, it is reactive equivalent of try with resources.

So your method should look like that:
```java
public static Mono<Void> saveBulk(ConnectionFactory connectionFactory, List<Rules> list) {
    String sql = "INSERT INTO public.rules (id, id1, id2, rule) VALUES ($1, $2, $3, $4)";
    return Mono.usingWhen(connectionFactory.create(), connection -> {
        Statement statement = connection.createStatement(sql);
        for (int i = 0; i < list.size(); i++) {
            Rules one = list.get(i);
            statement.bind(0, one.getId());
            statement.bind(1, one.getId1());
            statement.bind(2, one.getId2());
            statement.bind(3, one.getRule());
            if (i < list.size() - 1) {
                statement.add();
            }
        }
        return Flux.from(statement.execute())
            .flatMap(Result::getRowsUpdated)
            .then();
    }, Connection::close);
}
```

Keep in mind though that `statement.add` will keep all the bindings in memory until `statement.execute` is called so you probably want to implement some kind of batching by parts. I think `Flux.window` can help with that.

**Comment by toaster33** [comment]
Appreciate the quick response.  I tried using the createStatement().add() for each row but was not able to get all rows inserted within the timeframe needed but recall seeing the same memory issues.  Someone pointed me to [https://jdbc.postgresql.org/documentation/94/connect.html](reWriteBatchedInserts) but did not appear to work.  Also, thanks for correcting my Reactive (usingWhen).

**Comment by Squiry** [comment]
Try something like that:
```java
public static Mono<Void> saveBulk(ConnectionFactory connectionFactory, List<Rules> list) {
    int batchSize = 1024;
    String sql = "INSERT INTO public.rules (id, id1, id2, rule) VALUES ($1, $2, $3, $4)";
    return Mono.usingWhen(connectionFactory.create(), connection -> Flux.range(0, (list.size() / batchSize) + 1)
        .concatMap(j -> {
            int start = j * 1024;
            if (start >= list.size()) {
                return Mono.empty();
            }
            int end = Math.min(start + batchSize, list.size());
            Statement statement = connection.createStatement(sql);
            for (int i = start; i < end; i++) {
                Rules one = list.get(i);
                statement.bind(0, one.getId());
                statement.bind(1, one.getId1());
                statement.bind(2, one.getId2());
                statement.bind(3, one.getRule());
                if (i + 1 < end) {
                    statement.add();
                }
            }
            return Flux.from(statement.execute()).flatMap(Result::getRowsUpdated).then();
        })
        .then(), Connection::close);
}
```
Most of memory issues should be with the provided list then.

**Comment by toaster33** [comment]
Was able to get it working but unfortunately I cannot load the data (200k rows) within 10-15 secs.  Unclear which list you are referring to but if referring to "List<Rules> list", then I am unsure since I can run the code which generates the list not persist anything and my memory usage does not increase.  Only when i use createStatement() vs createBatch() do I see memory issues but I haven't touched many JVM arguments (as noted above).

**Comment by toaster33** [comment]
Appreciate your quick responses and helpful feedback, just wanted to share my findings in case others run into inserting a lot of rows using createStatement() as it seemed a little related to [Issue 492](https://github.com/pgjdbc/r2dbc-postgresql/issues/492).

**Comment by tuananh** [comment]
> Appreciate the quick response. I tried using the createStatement().add() for each row but was not able to get all rows inserted within the timeframe needed but recall seeing the same memory issues. Someone pointed me to [reWriteBatchedInserts](https://jdbc.postgresql.org/documentation/94/connect.html) but did not appear to work. Also, thanks for correcting my Reactive (usingWhen).

did you manage to make batch insert work?
