### ISSUE TITLE
CamlCase not supported

### ISSUE THREAD

**Issue by mmaryo** [pgjdbc/r2dbc-postgresql#505]
Hello 

I have to use Postgres DB with CamlCase everywhere and it seems not supported 

When I save an entity : 

```       
val abc = Entities(0, "TestABC")
entitiesRepository.save(abc).block()
```

`org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [INSERT INTO common."Entities" (Name, Code) VALUES ($1, $2)]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42703] column "name" of relation "Entities" does not exist`

It should be`Name`, not `name`

And the Entity 

```
@Table(schema = "common", name = "\"Entities\"")
data class Entities(
    @Column("Id") @Id var id: Long = 0,
    @Column("Name") var name: String = "",
    @Column("Code") var code: String = "",
)
```

Also, I tried to add \\" in fields name :   
```
@Table(schema = "common", name = "\"Entities\"")
data class Entities(
    @Column("\"Id\"") @Id var id: Long = 0,
    @Column("\"Name\"") var name: String = "",
    @Column("\"Code\"") var code: String = "",
)
```

The save worked, but the findAll() return empty Entities 
`Entities(id=0, name=, code=)`

I try query 

`entitiesRepository.findByName("abc").blockFirst()`

and exception is 
```
io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: column Entities.id does not exist
```
`id` should be `Id`

I use spring boot 3.0.0.M2, Kotlin 1.6, Jdk 17 and r2bcd 1.0.0.BUILD-SNAPSHOT

**Comment by mmaryo** [comment]
It's working perfectly with Dotnet, Dotnet created tables and fields with CamlCase, unfortunately 
Do you have solution for support CamlCase ?

**Comment by mp911de** [comment]
Generally, the driver passes through any SQL handed into the driver to the database without rewriting the SQL statement. Column and table names are a matter of your application or framework that generates SQL. When using Spring Data, you can enable global quoting and configure a `NamingStrategy`, see https://docs.spring.io/spring-data/jdbc/docs/current/api/org/springframework/data/relational/core/mapping/RelationalMappingContext.html.

Closing this ticket as we cannot do on the driver level anything for you.
