### ISSUE TITLE
Extend `PostgresqlSqlLexer` to handle PG14 SQL-standard function body syntax

### ISSUE THREAD

**Issue by mp911de** [pgjdbc/r2dbc-postgresql#512]
PG14 added a new syntax for creating SQL functions that we should support with `PostgresqlSqlLexer`

```sql
CREATE OR REPLACE FUNCTION asterisks(n int)
  RETURNS SETOF text
  LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
BEGIN ATOMIC
SELECT repeat('*', g) FROM generate_series (1, n) g; -- <-- Note this semicolon
END;
```

Right now, `PostgresqlSqlLexer.tokenize(…)` identifies this above as two statements. See also:

* pgjdbc/pgjdbc#2506
* npgsql/npgsql#4445

**Comment by toverdijk** [comment]
It does seem quite complex - I guess also the sql body needs to be parsed completely as well in order to catch commented out ENDs and such. I'll give it a shot..
