### ISSUE TITLE
Codec for money type

### ISSUE THREAD

**Issue by hantsy** [pgjdbc/r2dbc-postgresql#524]
Postgres provides a `money` type for financial case.

https://www.postgresql.org/docs/current/datatype-money.html

And there is a Java Money project to handle the Money type in Java, 

https://javamoney.github.io/

Is there a simple way to add Codec for `money` type, and convert to `BigDecimal`/Java Money's `MonetaryAmount`.

**Comment by davecramer** [comment]
The unfortunate part is that the Money type in PostgreSQL should never be used it has no notion of locale

**Comment by mp911de** [comment]
We could provide codecs for decimal numeric types to accept monetary values. With a money value type it is similar as with zoned temporals, that we can't store the currency part, basically, what Dave said.

**Comment by hantsy** [comment]
Check the money type doc, it requires a `lc_monetary` to set up the locale used in the currency. It can not accept multi-currency money types in the same database?

**Comment by davecramer** [comment]
No the money type doesn't really understand anything about currency. It's a very poorly designed type, please just don't use it
