### ISSUE TITLE
The driver doesn't support binding `String` for the type defined as `JSONB`

### ISSUE THREAD

**Issue by dstepanov** [pgjdbc/r2dbc-postgresql#525]
It is supported by the JDBC driver. In Micronaut Data we don't have a way to know what type the user has defined for the JSON representation in the DB and I don't think it should matter.

https://github.com/micronaut-projects/micronaut-data/issues/1574

Version: 0.9.1.RELEASE

**Comment by mp911de** [comment]
How does this work with JDBC? Postgres requires either a proper type specifier when sending JSON data for the bind value or the value must be cast in the SQL statement to JSON (`UPDATE … SET blob = $1::jsonb`).

**Comment by davecramer** [comment]
It appears we have no tests for this in the driver. I think you are correct you need to cast it in the insert, or update, but the reality remains we send and receive JSON or JSONB as a string. I'm guessing with prepared statements we could avoid the cast if we used setObject("some json", ...) but we don't have any code that proves that at the moment

**Comment by mp911de** [comment]
I agree that JSON is just text on the wire protocol. In the R2DBC driver, we have a [`Json`](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/Json.java) wrapper type to send the correct OID when binding parameters in the extended flow.

**Comment by davecramer** [comment]
which json type did you agree represented json in R2DBC ? I do think pgjdbc should address this.

**Comment by mp911de** [comment]
There's no JSON definition on the R2DBC spec level. Within the driver, we default to [`jsonb`](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/JsonCodec.java#L66). Users can, however, specify the type to use:

```java
Parameter in = Parameters.in(PostgresqlObjectId.JSON, "{\"hello\": \"world\"}");

// whatever was specified by the user
connection.createStatement("INSERT INTO my_table (my_json) VALUES($1)")
    .bind("$1", in).execute()

// default: jsonb
connection.createStatement("INSERT INTO my_table (my_json) VALUES($1)")
    .bind("$1", Json.of("{\"hello\": \"world\"}")).execute()

```

**Comment by davecramer** [comment]
ah, cool, must be nice not to have to write to a spec :)

**Comment by mp911de** [comment]
We also left out XML from the spec because proper support would require a lot of additional API for tree-parsing, and walking structures up to object mappers and that would have turned R2DBC into an XML and JSON overkill.

**Comment by davecramer** [comment]
never mind that fact that it is orthogonal to an RDBMS

**Comment by dstepanov** [comment]
I'm soorry, it looks like I was mistaken and there is no problem 😭
