### ISSUE TITLE
Cannot set connection password dynamically

### ISSUE THREAD

**Issue by mnbattaglia** [pgjdbc/r2dbc-postgresql#529]
We are using AWS RDS IAM to get a temporary access token that must be used as the connection password. This is valid only for 15 min, so we must obtain another token when creating a new connection.
By using a connection pool, the solution is to set a max life time with a less than 15 min duration (eg: 14 min) and connection should be re-created after that. There are several solutions in the web with JDBC implementations, where you can implement your own pool (eg: extending Hikari) and then overwrite the getPassword function, calling the proper AWS method to get the token at that moment.

I'm trying a similar approach with r2dbc-pool and r2dbc-postgres, but cannot get to hook while creating the connection.
The pool instantiates a PostgresqlConnectionFactory via the PostgresqlConnectionFactoryProvider. While building this connection factory, a PostgresqlConnectionConfiguration is sent to the PostgresqlConnectionFactory constructor with all connection configuration already set from Options. When a connection is needed to be created in a later phase (first connection pool interaction), the PostgresqlConnectionFactory will call the getAuthenticationHandler to create the auth message. The thing is, at this point the password is kept internally in the PostgresqlConnectionConfiguration with the value fixed.

What we need is to provide a way to resolve the password dinamically (a function should be called at that moment).

One approach could be extend the PostgresqlConnectionFactoryProvider so it can create the PostgresqlConnectionFactory but providing an extended version of the PostgresqlConnectionConfiguration which resolves the password dinamically. The problem we have is that ALL classes are final and there is no way to extend.

Is there any other way we can resolve this? I believe that using this dynamic password mechanism is a fair usecase.

Thanks in advance

**Comment by mp911de** [comment]
There's no built-in support to obtain credentials from a function. However, when using R2DBC pool you can create an own publisher from e.g. `Mono.deferred(...)` that returns a fresh `PostgresConnectionFactory.create()` publisher. The deferred mono would always spin up a new connection factory configured with the most recent password.

**Comment by mnbattaglia** [comment]
Thanks @mp911de for the quick response! Sorry, but I'm not quite following. Are you suggesting to implement my own ConnectionFactory that wraps a PostgresConnectionFactory which delegates the create method and then configure the pool to use that factory? Thanks again and a solution will be really appreciated.

**Comment by mp911de** [comment]
Yes, something along those lines. The code should look like the following:

```java
ConnectionFactoryOptions options = ConnectionFactoryOptions.parse("r2dbc:postgresql://host/database");

ConnectionFactory connectionFactoryStub = ConnectionFactories.get(options);

Mono<? extends Connection> connectionPublisher = Mono.defer(() -> {
    
    ConnectionFactoryOptions optionsToUse = options.mutate()
        .option(ConnectionFactoryOptions.USER, "…") // provide a new username each time we see a connect request
        .option(ConnectionFactoryOptions.PASSWORD, "…") // provide a new password each time we see a connect request
        .build();

    return Mono.from(ConnectionFactories.get(optionsToUse).create());
});

ConnectionFactory myCustomConnectionFactory = new ConnectionFactory() {

    @Override
    public Publisher<? extends Connection> create() {
        return connectionPublisher;
    }

    @Override
    public ConnectionFactoryMetadata getMetadata() {
        return connectionFactoryStub.getMetadata();
    }
};

ConnectionPoolConfiguration poolConfiguration = ConnectionPoolConfiguration.builder().connectionFactory(myCustomConnectionFactory).build();
ConnectionPool pool = new ConnectionPool(poolConfiguration);
// …
```

**Comment by mnbattaglia** [comment]
Thanks @mp911de . Will give it a try. If I remember well I tried a similar approach but somehow the creation method of the factory was called just once and then the pool creates multiple connections internally, using the original configuration. But in that case I don't recall using a defer. Anyway, will try it out and thanks again!

**Comment by mnbattaglia** [comment]
Hey @mp911de , you example was a lifesaver. It was as I said. I had exactly the same approach but my mistake was in the create() delegate: I was returning the connectionFactoryDelegate.create() directly instead of wrapping it in a defer (newbie reactor mistake). After trying it with a defer, it works exactly as expected! Every time a connection is created (when populating the pool with initial size, when a connection expires and needs to be regenerated, etc.) the deferred logic is called. So, thanks a lot @mp911de!

**Comment by vsantwana** [comment]
Hey @mp911de @mnbattaglia 
I have a doubt regarding this solution.
This makes it impossible to set either the initial pool size or the max pool size, which are amongst the most common configuration for a connection pool. Making a connection factory everytime makes it a necessity to keep both the `PoolingConnectionFactoryProvider.INITIAL_SIZE` and `PoolingConnectionFactoryProvider.MAX_SIZE` because every connection needs a new password. 
So if I want 10 initial connections for my application, I need 10 new `ConnectionFactory`, but specifying `ConnectionPoolConfiguration.initialSize`or  `ConnectionPoolConfiguration.maxSize` doesn't work. 

@mnbattaglia how do you restrict the initial connection pool size and the maximum connection pool size?
