### ISSUE TITLE
Requires access to the ParseSql class

### ISSUE THREAD

**Issue by geliotropv** [pgjdbc/r2dbc-postgresql#537]
## Feature Request

Ability to make the ParsedSql class available from outside

#### Is your feature request related to a problem? Please describe

Faced the problem of adding parameters in sql query. The situation is such that we use requests that can change from the configuration file, which leads to the fact that it is not known in advance which parameters can be in it.

#### Describe the solution you'd like

```
package org.springframework.r2dbc.core
public class ParsedSql {}
```

#### Describe alternatives you've considered

Or a functional for reading such parameters from a string sql query

**Comment by Squiry** [comment]
I thing that `org.springframework` package questions should be asked in a [Spring Framework](https://github.com/spring-projects/spring-framework/blob/main/spring-r2dbc/src/main/java/org/springframework/r2dbc/core/ParsedSql.java) repository.
