### ISSUE TITLE
Associate `PostgresConnectionClosedException` with error code `08006`

### ISSUE THREAD

**Issue by rgmz** [pgjdbc/r2dbc-postgresql#538]
#### Is your feature request related to a problem? Please describe

When the connection is closed unexpectedly it throws a `PostgresConnectionClosedException`. I would like to handle this scenario programmatically, however, it currently isn't possible to catch `PostgresConnectionClosedException` because it's package-private.

https://github.com/pgjdbc/r2dbc-postgresql/blob/a32a679bc196c872d0929a1fd157cccfb2dd9cf3/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L554-L564

For example, if I'm [listening to notifications and want to restart the connection or channel](https://github.com/mp911de/r2dbc-postgres-notification-example/blob/main/src/main/java/com/example/demo/DemoApplication.java).

#### Describe the solution you'd like

I would like for `PostgresConnectionClosedException` to be public so it can be explicitly caught.

#### Describe alternatives you've considered

Presently the only alternative I'm aware of is catching `R2dbcNonTransientResourceException` and [checking for the "UNEXPECTED" error message](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L96). This isn't ideal because it's not as clear as catching the specific exception, and the message could change in the future.

**Comment by mp911de** [comment]
Any `R2dbcNonTransientResourceException` that does not implement the `PostgresqlException` is an exceptional state that requires recovery. Driver exceptions that implement `PostgresqlException` are error notifications sent by the database. `PostgresConnectionClosedException` is a client-side exception and therefore it does not implement `PostgresqlException`.

We do not want to expose internal exception types as the specification already defines a public API for exception signals.

**Comment by rgmz** [comment]
> We do not want to expose internal exception types as the specification already defines a public API for exception signals.

Would including specific error codes in [`R2dbcNonTransientResourceException`](https://github.com/r2dbc/r2dbc-spi/blob/01c39070135c33c37152452c00bbc36c980a2eff/r2dbc-spi/src/main/java/io/r2dbc/spi/R2dbcNonTransientResourceException.java#L73-L75) be a viable alternative? The [MariaDB implementation](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/8ee91691157831683e2e44d3ae3107560c9cd577/src/main/java/org/mariadb/r2dbc/ExceptionFactory.java#L40-L43) includes relevant error codes (e.g. [`0800`](https://mariadb.com/kb/en/failover-and-high-availability-with-mariadb-connector-j-for-2x-driver/#application-concerns)), and including [Postgres error codes](https://www.postgresql.org/docs/current/errcodes-appendix.html) would be more meaningful than matching the exception reason.

**Comment by mp911de** [comment]
Thanks for the suggestion. Reporting connection failure with the error code `08006` makes sense.
