### ISSUE TITLE
0.9.0.RC1 Regression in "INSERT on conflict do update": Bound parameter count does not match parameters in SQL statement

### ISSUE THREAD

**Issue by artem-zinnatullin** [pgjdbc/r2dbc-postgresql#548]
## Bug Report

After update of r2dbc-posgresql in our project to `0.9.0.RC1` from `0.9.0.M1` our integration tests found a bug in execution of an SQL statement that is working normally on `0.9.0.M1`.

It throws "Bound parameter count does not match parameters in SQL statement" (stacktrace and SQL statement below).

#### Versions

- Driver: 0.9.2.RELEASE, was updated from 0.9.0.M1
- Database: PostgreSQL 14.5 Debian 14.5-1.pgdg110+1
- Java: eclipse-temurin:17-jre-focal (Docker image)
- OS: Debian

#### Current Behavior

We have an SQL statement that is performing an `INSERT` with `on conflict` `do update` that throws exception on `0.9.0.RC1` but is working normally on `0.9.0.M1`.

<details>
<summary>Stack trace</summary>

```java
// your stack trace here
java.lang.IllegalStateException: Bound parameter count does not match parameters in SQL statement
	at io.r2dbc.postgresql.client.Binding.validate(Binding.java:176)
	at java.base/java.util.ArrayDeque.forEach(Unknown Source)
	at io.r2dbc.postgresql.PostgresqlStatement.execute(PostgresqlStatement.java:208)
	at io.r2dbc.postgresql.PostgresqlStatement.execute(PostgresqlStatement.java:144)
	at io.r2dbc.postgresql.PostgresqlStatement.execute(PostgresqlStatement.java:58)
```

</details>
 
#### SQL Query

<details>
<summary>Query</summary>

```sql
-- your SQL here;
insert into my_table(my_key, update_time_utc, create_time_utc, size, counter)
                values ($1, $2, $3, $4, $5) on conflict (my_key) 
                    do update set ac_ref_count = my_table.counter + 1
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```kotlin
// your code here;
val insert = connection.createStatement(query)
insert
    .bind(0, key)
    .bind(1, timestamp)
    .bind(2, timestamp)
    .bind(3, size)
    .bind(4, 1)
    .add()

insertBazelCas
    .execute()
    .asFlow()
    .collect { it.rowsUpdated.awaitSingle() }
```

</details>

#### Expected behavior/code

SQL statement should be executed normally.

**Comment by artem-zinnatullin** [comment]
Update: nailed it down to `0.9.0.RC1`, code works on `0.9.0.M1`, fails on `0.9.0.M1`

**Comment by mp911de** [comment]
The problem is the lingering call to `add()` that prepares the statement for another set of parameter bindings. If you remove `.add()`, then everything will work.

Batching (`.add()`) is typically used as:

```java
insert
    .bind(0, key)
    .bind(1, timestamp)
    .bind(2, timestamp)
    .bind(3, size)
    .bind(4, 1)
    .add()
    .bind(0, key1)
    .bind(1, timestamp1)
    .bind(2, timestamp1)
    .bind(3, size1)
    .bind(4, 2)
    .execute()
```

**Comment by artem-zinnatullin** [comment]
@mp911de you're absolutely right 🤦‍♂️ this fixed the issue and we were able to update.

Thanks for your work on this project btw!
