### ISSUE TITLE
Interval.parse doesn't parse week

### ISSUE THREAD

**Issue by emilwihlander** [pgjdbc/r2dbc-postgresql#565]
#### Versions

- Driver: 1.0.0.RELEASE
- Database: 14
- Java: 17
- OS: macOS

#### Current Behavior

When trying to parse a week interval an empty (all values 0) Interval is returned.

 
#### Steps to reproduce

`Interval.parse("1 week").toString() == Interval.ZERO.toString()`

#### Expected behavior/code

That weeks are parsed as 7 days per week

**Comment by emilwihlander** [comment]
I have a local version supporting all additional postgresql interval units: millennium, century, decade, week. I will create a PR soon

**Comment by mp911de** [comment]
Thanks a lot, happy to review your changes.
