### ISSUE TITLE
Could someone build artifact for 1.0.0 RELEASE and upload it to maven central?

### ISSUE THREAD

**Issue by ViacheslavSamsonov** [pgjdbc/r2dbc-postgresql#576]
Now in https://mvnrepository.com/artifact/io.r2dbc/r2dbc-postgresql available only version 0.8.13.RELEASE.
It would be nice if someone build and upload the latest version of this driver.

**Comment by mp911de** [comment]
What you're looking for is at https://repo1.maven.org/maven2/org/postgresql/r2dbc-postgresql/1.0.0.RELEASE/ as the groupId has changed over time.
