### ISSUE TITLE
Enhance ConnectionFactoryOptions to support all available SSL modes

### ISSUE THREAD

**Issue by DennisPietruck0001** [pgjdbc/r2dbc-postgresql#609]
## Feature Request

Currently, when creating a PostgreSQL connection using ConnectionFactoryOptions, we have limited options for configuring the sslmode. The library primarily enforces the use of the verify-full SSL mode or disable

However, PostgreSQL offers a range of SSL modes, including disable, allow, prefer, require, verify-ca, and verify-full, each catering to different security requirements and performance considerations. To accommodate a broader range of use cases, I propose to modify ConnectionFactoryOptions to allow users to specify their preferred SSL mode when establishing a PostgreSQL connection. This enhancement will provide greater flexibility and adaptability for different security and performance needs.

#### Describe the solution you'd like

I would like to mark the ssl option as deprecated and introduce a new option named sslmode. Which allows to select from all available sslmodes.

#### Describe alternatives you've considered

The primary alternative I've considered is setting the sslmode directly in the connection string when creating a PostgreSQL connection. While this approach does work and allows for the desired SSL mode configuration, it deviates from our preferred development convention.

**Comment by mp911de** [comment]
I'm not quite sure what you're asking for. Our `SSLMode` enumeration lists the options you mentioned:

https://github.com/pgjdbc/r2dbc-postgresql/blob/543f5ccbd7797a1b7d8a2520a159dc55a1a48aab/src/main/java/io/r2dbc/postgresql/client/SSLMode.java#L20-L53

Care to elaborate?

**Comment by DennisPietruck0001** [comment]
Maybe I haven't found the right place, but how can I use this enumeration when I want to create new connection?

```java
ConnectionFactories.get(
    ConnectionFactoryOptions
        .builder()
        .from(ConnectionFactoryOptions.parse("r2dbc://localhost:3306/my_database"))
        .option(ConnectionFactoryOptions.SSL, true) // sets sslmode to verify-full
        .option(ConnectionFactoryOptions.SSL, false) // sets sslmode to disable
        .option(ConnectionFactoryOptions.SSL, SSLMode.REQUIRE) // this is not possible
        .option(ConnectionFactoryOptions.SSL_MODE, SSLMode.REQUIRE) // maybe we can add a new option
        .build()
)
```

**Comment by mp911de** [comment]
Check our the ConnectionFactory options at https://github.com/pgjdbc/r2dbc-postgresql#getting-started

Using an URL `r2dbc://localhost:3306/my_database?sslMode=PREFER` or programmatically, `option(Option.valueOf("sslMode"), SLMode.REQUIRE)` (`option(Option.valueOf("sslMode"), "require")`) will get you there.

ConnectionFactory options are pretty lenient so that you can use either String-based values or the Driver-specific API to enable various ways of configuration.

**Comment by DennisPietruck0001** [comment]
I wasn't aware of the `Option.valueOf("sslMode")` way. Thank you!
