### ISSUE TITLE
Support for pgvector

### ISSUE THREAD

**Issue by liemng** [pgjdbc/r2dbc-postgresql#612]
#### Is your feature request related to a problem? Please describe

Support for pgvector.

#### Describe the solution you'd like

Support for pgvector similar to Hibernate: https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#vector-module

**Comment by mp911de** [comment]
How exactly you envision support for PG Vector with a library that requires you to provide SQL?

**Comment by davecramer** [comment]
@mp911de how do you support custom types today? The only "support" that is possible in pgjdbc is to allow sending and receiving the vector in binary. Is that possible ? Pretty significant performance possible with binary mode.

**Comment by mp911de** [comment]
We have a Codec API that can be extended by the driver or any external Codec

https://github.com/pgjdbc/r2dbc-postgresql/blob/543f5ccbd7797a1b7d8a2520a159dc55a1a48aab/src/main/java/io/r2dbc/postgresql/codec/BuiltinDynamicCodecs.java#L55-L65

By parsing type/OID information, one could come up with any kind of wrapper that makes sense.

**Comment by davecramer** [comment]
Cool, so there are significant savings to be had by sending and receiving vectors in binary!

**Comment by liemng** [comment]
Yeah, exactly it, @mp911de.  It would be nice to have a built-in codec for pgvector, given the popularity of LLMs nowadays.

**Comment by mp911de** [comment]
Thanks for clarifying. It sounded at first like an object mapper feature.
Am 5. Dez. 2023, 18:21 +0100 schrieb Liem Nguyen ***@***.***>:

**Comment by davecramer** [comment]
FWIW, I didn't implement it in pgjdbc, rather in pg_vector java support. I don't think it matters where it's implemented.

**Comment by mp911de** [comment]
That's in place now, including support for 1-dimensional vector arrays (array of vectors).

**Comment by mp911de** [comment]
Please give the new `Vector` codec a try, it's available from 1.1.0 and 1.0.3 snapshots via oss sonatype.

**Comment by mp911de** [comment]
I would want to wait for today's Reactor release before shipping a new release.

**Comment by chrischall** [comment]
Apologies for the comment here vs. a bug report, but PostgreSQL 8.2 and below to not have `pg_catalog.pg_type.typarray`: 
https://www.postgresql.org/docs/8.2/catalog-pg-type.html

AWS Redshift is based on PostgreSQL 8.0.2:
https://docs.aws.amazon.com/redshift/latest/dg/r_VERSION.html

As such, this driver can no longer be used to connect to AWS Redshift.

**Comment by mp911de** [comment]
Pleas downgrade to 1.0.2 for the time being. I filed #621 to fix the regression.
