### ISSUE TITLE
Row.get(Object) decodes VARCHAR columns as CHAR

### ISSUE THREAD

**Issue by mp911de** [pgjdbc/r2dbc-postgresql#9]
Calling `Row.get(identifier)` or `Row.get(identifier, Object.class)` decodes `VARCHAR` values as chars. The result is that only the first character of the string is returned.

**Comment by nebhale** [comment]
This isn't the only conflict (which is why being explicit where you can is useful), but I'm going to set the priorities as:

* `ShortCodec` <= `ByteCodec`
* `StringCodec` <= `CharacterCodec`, `EnumCodec`, `UriCodec`, `UrlCodec`, `ZoneIdCodec`
* `InstantCodec` <= `DateCodec`
